app = "clinical-trials-api"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[env]
  CT_GOV_BASE_URL = "https://clinicaltrials.gov/api/v2/studies"
  BATCH_SIZE = "500"
  LOG_LEVEL = "INFO"
  PORT = "8080"
